server:
  port: 8080

datasource:
  url: jdbc:h2:tcp://localhost/~/testDb
  username: sa
  password:
  driver-class-name: org.h2.Driver

jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      format_sql: true
      auto_quote_keyword: true
      dialect: org.hibernate.dialect.H2Dialect

logging.level:
  org.hibernate.SQL: debug